# Generated by Django 3.1.2 on 2021-12-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_cidade_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='capital',
            field=models.BooleanField(default=False, help_text=' Marcar se a cidade for capital.'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
