version: '3.5'

services:

  app:
    build: .
    volumes:
      - .:/code
    entrypoint: ['sh', 'run-django.sh']
    depends_on:
      - personal_db
    networks:
      - database
      - web

  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d/
      - ./log/nginx:/var/log/nginx
      - ./static:/var/www/static
      - ./media:/var/www/media
    depends_on:
      - app
    networks:
      - web

  pessoal_db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pessoal
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    networks:
      - database

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
volumes:
  postgres-data-prod:
  portainer-data:

networks:
  web:
  database: