version: '3.5'

services:

  local_db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/local-data

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  postgres-data:
